#!/usr/bin/env /bin/bash
binary_path=$AGENT_ROOT_DIR
echo LD_LIBRARY_PATH = $LD_LIBRARY_PATH
echo sudo -E ${binary_path}mpixexec.bin $@
sudo -E env "PATH=$PATH" "LD_LIBRARY_PATH=$LD_LIBRARY_PATH" ${binary_path}mpixexec.bin $@
