#ifndef RUNTIMECTX
#define RUNTIMECTX

enum MPI_TYPES {MPIX_CHAR=0, MPIX_BYTE, MPIX_SHORT, MPIX_INT, MPIX_LONG, MPIX_FLOAT, MPIX_DOUBLE, MPIX_UNSIGNED_CHAR, MPIX_UNSIGNED_SHORT, MPIX_UNSIGNED, MPIX_UNSIGNED_LONG, MPIX_LONG_DOUBLE, MPIX_LONG_LONG_INT, MPIX_COMPOBJ};

//leave it to struct initialization

struct runtime_ctx
{


};

#endif

