#ifndef RUNTIMECTX
#define RUNTIMECTX

enum MPI_TYPES 
{
  MPIX_CHAR=0, 
  MPIX_BYTE, 
  MPIX_SHORT, 
  MPIX_INT, 
  MPIX_LONG, 
  MPIX_FLOAT, 
  MPIX_DOUBLE, 
  MPIX_UNSIGNED_CHAR, 
  MPIX_UNSIGNED_SHORT, 
  MPIX_UNSIGNED, 
  MPIX_UNSIGNED_LONG, 
  MPIX_LONG_DOUBLE, 
  MPIX_LONG_LONG_INT, 
  MPIX_COMPOBJ,
  MPIX_NORMAL_MARKER,

  MPIX_INT_CHAR, 
  MPIX_INT_BYTE, 
  MPIX_INT_SHORT, 
  MPIX_INT_INT, 
  MPIX_INT_LONG, 
  MPIX_INT_FLOAT, 
  MPIX_INT_DOUBLE, 
  MPIX_INT_UNSIGNED_CHAR, 
  MPIX_INT_UNSIGNED_SHORT, 
  MPIX_INT_UNSIGNED, 
  MPIX_INT_UNSIGNED_LONG, 
  MPIX_INT_LONG_DOUBLE, 
  MPIX_INT_LONG_LONG_INT, 
  MPIX_INT_COMPOBJ,
  MPIX_INTERNAL_MARKER,

  MPIX_REF_CHAR, 
  MPIX_REF_BYTE, 
  MPIX_REF_SHORT, 
  MPIX_REF_INT, 
  MPIX_REF_LONG, 
  MPIX_REF_FLOAT, 
  MPIX_REF_DOUBLE, 
  MPIX_REF_UNSIGNED_CHAR, 
  MPIX_REF_UNSIGNED_SHORT, 
  MPIX_REF_UNSIGNED, 
  MPIX_REF_UNSIGNED_LONG, 
  MPIX_REF_LONG_DOUBLE, 
  MPIX_REF_LONG_LONG_INT, 
  MPIX_REF_COMPOBJ,
  MPIX_END_MARKER

};

//leave it to struct initialization

struct runtime_ctx
{


};

#endif

